wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1644224417
    t:
      4: 3.8.12
      5: 0.12.10
      8:
      - 5
